FROM rust:1.74.1-alpine3.17 AS chef
USER root

RUN apk add --no-cache musl-dev & cargo install cargo-chef
WORKDIR /auth-microservice

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /auth-microservice/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
RUN apk add --no-cache protoc
COPY . .
RUN cargo build --release --bin auth

# We do not need the Rust toolchain to run the binary!
FROM debian:buster-slim AS runtime
WORKDIR /auth-microservice
COPY --from=builder /auth-microservice/target/release/auth /usr/local/bin
ENTRYPOINT ["/usr/local/bin/auth"]